version: '3'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=test
    environment:
      - BUILD_HASH=${BUILDKITE_COMMIT}

  app-production: &production
    build: .
    environment:
      - BUILD_HASH=${BUILDKITE_COMMIT}

  app-staging:
    <<: *production
