name: Cleanup Registry

on:
  schedule:
    - cron: '0 0 * * 1' # https://crontab.guru/#0_0_*_*_1
  workflow_dispatch:

env:
  IMAGE_NAMES: arora-discord

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete old versions
        uses: snok/container-retention-policy@96e897805acf21aa2ebc21fdf8e04c879e7daf9d # v2.0.1
        with:
          image-names: ${{ env.IMAGE_NAMES }}
          cut-off: 2 days ago UTC
          account-type: personal
          skip-tags: latest,staging
          token: ${{ secrets.GH_PAT }}
